### ISSUE TITLE
Extending UI Grid Fail

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-samples#18]
Hi @megafreeman,

I according to your  docs(https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/extend-ui-grid-editable) to extending UI grid,  I want to extend my order blade to add the special address's email, but always fail, then I install your module directly, and get the same result, I can't get the extend column, could you help me?
Thank you very much!

ENV:
 Platform 2.13.44
 Price Module: 2.18.6
 Ext Price Module: 1.0.0

BR,
Ruyi

**Comment by yecli** [comment]
Please check this sample:
https://github.com/VirtoCommerce/vc-samples/tree/master/External.PricingModule

Also you could regenerate migration in Picing module to get actual model state here.

**Comment by ruyi-kooboo** [comment]
Hi  @yecli ,
Thank you for your answer.
Yes, I followed this example, but I couldn't display it correctly, so I used the example to generate a module and install it, and found that I didn't see the extended columns either, I don't know if the example is still valid. Could you check it? Thanks again. :)

BR,
Ruyi

**Comment by yecli** [comment]
We updated this sample 2 month ago, it should be tested that time.
As you have no module loading errors, seems it is something with script/options caching.
Could you please check if scripts are not cached by the browser (e.g. Disable cache is checked in DevTools)?
![image](https://user-images.githubusercontent.com/15610352/61627223-a97c1a80-ac98-11e9-940c-43c541c75409.png)

Thus you should be able to see [extension module script ](https://github.com/VirtoCommerce/vc-samples/blob/master/External.PricingModule/External.PricingModule/External.PricingModule.Web/Scripts/module.js) in Sources for this module (or in module bundle).

If it won't help, please try to clear Local Storage in browser for your site (grid settings could be cached hrer):
![image](https://user-images.githubusercontent.com/15610352/61627359-fcee6880-ac98-11e9-8585-65cfdc89b259.png)

**Comment by ruyi-kooboo** [comment]
Hi @yecli,
Strange, I did what you said, but the result is the same, I don't know why. Anyway, thanks for your solutions

BR,
Ruyi

**Comment by ruyi-kooboo** [comment]
Hi @yecli，
I think I know the reason now, Because in the case of no value, it doesn't show up on the front-end (It maybe be ignored when it serialized to json), and then the Grid doesn't show up if the field mapping fails

Thanks,
BR,
Ruyi

**Comment by yecli** [comment]
Hi @ruyi-kooboo.
Indeed, if you have no values for the field, it will not show up in the grid.
If your problem is solved, please close the issue.

**Comment by ruyi-kooboo** [comment]
Hi @yecli ,
Okay, Thanks a lot.

BR,
Ruyi
